#!/bin/csh -f  
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --time=10:00:00 
#SBATCH --job-name={runname}
#SBATCH --output=out_err/slurm_%j.out
#SBATCH --error=out_err/slurm_%j.err 
#SBATCH --export=ALL
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=reusebi@caltech.edu


# === Default test run script for idealized GCM ===
# For T42 resolution, use 2 tasks, 8 cpus per task. simulated time is about 1 day/min. 
# So T42 simulation for 800 days should request about 15 hours to be comfortable.
# for T85 resolution, use 4 tasks, 8 cpus per task. simulated time is about 1 day/min
# For 800 days, request 18 hours to be safe
 
# Ian Eisenman, Yohai Kaspi, Tim Merlis, November 2010
# Farid Ait Chaalal, Xavier Levine, Zhihong Tan, March 2012 
# Farid Ait Chaalal, September 2012
# Robb Wills, Zhihong Tan, August 2013
# Robb Wills, Ori Adam, May 2014
# Lenka Novak, Oct 2018 

# The following variables below are passed as arguments to the script
# runname: Name of the run (includes most of the variables below in it)
# delh: Heating rate parameter controlling strength of tropical heating (K/day)
# gamma: Convective stability parameter controlling static stability (dimensionless)
# phi0: Center latitude of forcing (degrees)
# radius: Radius of forcing region (dimensionless)
# omega: Rotation rate relative to Earth's rotation (dimensionless) 
# drag: Surface drag coefficient (dimensionless)
# res: Resolution of model ('T42' or 'T85')
# freediff: Whether to use free atmospheric diffusion (True/False)
# diff_coef: Vertical diffusion coefficient (m^2/s)
# axisymm: Whether to use axisymmetric forcing (True/False)
# Tsfcavg: Mean surface temperature (K)
# kadays: Newtonian cooling timescale in free atmosphere (days)
# ksdays: Surface thermal damping timescale (days)
# sigmab: Sigma level of boundary layer top (dimensionless)
# sigmalat: Width of forcing region in latitude (degrees)
# tauc: Convective adjustment timescale (seconds)
# days: Length of each model integration (days)
# runs_per_script: Number of consecutive model runs within this script
# start_analysis: Script run to start analysis from

set delh = {delh}
set gamma = {gamma}
set phi0 = {phi0}
set radius = {radius}
set omega = {omega}
set drag = {drag}
set res = {res}
set freediff = {freediff}
set diff_coef = {diff_coef}

set axisymm = {axisymm}
set Tsfcavg = {Tsfcavg}
set kadays = {kadays}
set ksdays = {ksdays}
set sigmab = {sigmab}
set sigmalat = {sigmalat}
set tauc = {tauc}
set days = {days}
set runs_per_script = {runs_per_script}
set start_analysis = {start_analysis}
set runname = {runname}

set moldiff = .false.

if ("$res" == "T42") then
  set num_fourier = 42
  set num_spherical = 43
  set lon_max = 128
  set lat_max = 64
else if ("$res" == "T85") then
  set num_fourier = 85
  set num_spherical = 86
  set lon_max = 256
  set lat_max = 128
endif

set damping_option = 'resolution_dependent'
set damping_order = 4
set damping_coeff = 6.9444444e-05

if ("$axisymm" == "True") then
  set axisymm = 0
  set damping_coeff = 2.0e-04
else
  set axisymm = 2
endif

if ("$freediff" == "True") then
  set freediff = .true.
else
  set freediff = .false.
endif


# change the working directory (default is home directory)                       
cd $SLURM_SUBMIT_DIR
echo $SLURM_SUBMIT_DIR 
limit stacksize unlimited 

# source required modules (HPC) 
source /etc/profile.d/modules.csh
 

set od = od
set restart_workdir = ""

# testbordoniphi020_50sigma
# testbordoniphi020_T85

set model_type     = dry                         # if "moist", the moist model is run and if "dry, it is the dry. "moist_hydro" is for the bucket hydrology model. The namelists for the parameters are below (L212). 
set machine        = hpc                          # machine = euler or brutus, use the alternate runscripts for fram, or change mkmf templates, submission commands, and modules for other machines
set analysis_type  = 2d                             # choose type of analysis: 2d (zonally averaged) or 3d (zonally varying) outputs

set run_script     = $cwd/run_exp                  # path/name of this run script (for resubmit) 

set exp_home       = $cwd:h                         # directory containing run/$run_script and input/ 
set exp_name       = $exp_home:t                    # name of experiment (i.e., name of this model build) 
set fms_home       = $cwd:h:h:h/idealized           # directory containing model source code, etc, usually /home/$USER/fms/idealized
set home_dir       = $cwd:h:h:h:h

# SET UP PERSONAL DIRECTORY ON SCRATCH DISC
set work_dir     = /resnick/scratch/$USER/fms_output

echo $fms_home 
 
                            # number of script run at which to start analysis (after spin-up) 
set num_script_runs = 1                              # how many times to resubmit script to queue
set days_per_segment = 1 #${{days}}                       # days per segment of analysis (for seasonally-varying analysis)

@ num_segments       = ${{days}} / ${{days_per_segment}} # number of analysis segments
echo num_segments    = $num_segments

# find data directory location, 

set tmpdir1 = ${{work_dir}}/fms_tmp/${{exp_name}} 

set echo  
# Tell me which nodes it is run on; for sending messages to help-hpc           
echo " "
echo "*** Running ${{run_script}} on $HOSTNAME ***"
echo " "
date

#----------------------------------------------------------------------

# zonally averaged analysis 
set analysis_version = analysis_python
set analysis_script = fms_analysis.sh
set diagtable   = $exp_home/input/diag_table_${{model_type}}_${{analysis_type}}     # path to diagnostics table

set analysis_dir = ${{fms_home:h}}/analysis/$analysis_version/run                 # location of analysis directory

#--------------------------------------------------------------------------------------------------------

# source /etc/profile.d/modules.csh
# if (${{machine}} == euler) then 
#     module load new
#     module load intel/14.0.1
#     module load open_mpi/1.6.5
# else
#     module load intel/12.1.2
#     module load open_mpi/1.4.5
# endif

module purge
module load intel-oneapi-compilers-classic/2021.10.0-gcc-11.3.1-q7zzs5v
module load intel-oneapi-mpi/2021.10.0-gcc-11.3.1-xj5ixri
module load netcdf-fortran/4.6.1-oneapi-2023.2.1-llc6kws

# module load intel-oneapi-compilers/2023.2.1-gcc-13.2.0-qlb6hkr 
# module loa intel-oneapi-mpi/2021.11.0-oneapi-2023.2.1-atn5hhn

echo "Launcher:" `which srun`

set NPROCS=$SLURM_NTASKS
echo This job has allocated $NPROCS processors

#--------------------------------------------------------------------------------------------------------

limit stacksize unlimited 

cd $exp_home 
 
# define variables
set run_dir     = $tmpdir1/$runname                 # tmp directory for current run
set workdir     = $run_dir/workdir                   # where model is run and model output is produced
set output_dir  = $run_dir/output                    # output directory will be created here
set platform    = ifc                                # a unique identifier for your platform

# note the following init_cond's are overwritten later if reload_commands exists
set init_cond   = ""

set pathnames   = $exp_home/input/path_names                       # path to file containing list of source paths
echo "$pathnames"


set namelist    = $exp_home/input/namelists_${{model_type}}          # path to namelist file
set fieldtable  = $exp_home/input/field_table_${{model_type}}        # path to field table (specifies tracers)
set execdir     = $run_dir/exe.fms                                  # where code is compiled and executable is created
set run_analysis = $run_dir/analysis                               # where analysis is run
set analysis_out_err = $run_analysis/out_err                       # out and err for analysis
set mppnccombine = $run_dir/mppnccombine.$platform                  # path to executable mppnccombine
set template    = $fms_home/bin/mkmf.template.${{platform}}_${{machine}}_mpi # path to template for your platform
set mkmf        = $fms_home/bin/mkmf                               # path to executable mkmf
set sourcedir   = $fms_home/src                                    # path to directory containing model source code
set time_stamp  = $fms_home/bin/time_stamp.csh                     # generates string date for file name labels

set ireload     = 1                                  # counter for resubmitting this run script
set irun        = 1                                  # counter for multiple model submissions within this script

#--------------------------------------------------------------------------------------------------------

# if exists, load reload file 

set reload_file = ${{run_dir}}/reload_commands 

if ( -d $run_dir )  then
  if ( -f $reload_file ) then
     # set irun, ireload, init_cond
    #  source $reload_file
    echo 'reload file exists for some reason - ignoring it'
  endif
endif

#--------------------------------------------------------------------------------------------------------

# setup directory structure
if ( ! -d $execdir ) mkdir -p $execdir
if ( ! -d $run_analysis ) mkdir -p $run_analysis
if ( ! -d $analysis_out_err ) mkdir -p $analysis_out_err

if ( $restart_workdir != "") then
    cp -rf $restart_workdir $workdir 
    mkdir $workdir/INPUT $workdir/RESTART
    echo "WARNING: Using $restart_workdir for restart."
else
  if ( ! -e $workdir ) then
    mkdir $workdir $workdir/INPUT $workdir/RESTART
  else
    rm -rf $workdir
    mkdir $workdir $workdir/INPUT $workdir/RESTART
    echo "WARNING: Existing workdir $workdir removed."
  endif
endif

if ( ! -d $output_dir )  then
  mkdir -p $output_dir
endif
if ( ! -d $output_dir/combine ) then
  mkdir -p $output_dir/combine  
endif
if ( ! -d $output_dir/logfiles ) then
  mkdir -p $output_dir/logfiles
endif
if ( ! -d $output_dir/restart ) then
  mkdir -p $output_dir/restart
endif

#--------------------------------------------------------------------------------------------------------

# compile mppnccombine.c, needed only if $npes > 1
if ( ! -f $mppnccombine ) then
  gcc -O -o $mppnccombine -I$fms_home/bin/nc_inc -L$fms_home/bin/nc_lib $fms_home/postprocessing/mppnccombine.c -lnetcdf 
endif

#--------------------------------------------------------------------------------------------------------

# compile the model code and create executable

# append fms_home (containing netcdf libraries and include files) to template
/bin/cp $template $workdir/tmp_template
# echo "fms_home = $fms_home" >> $workdir/tmp_template


# Prepend fortran files in srcmods directory to pathnames. 
# Use 'find' to make list of srcmod/*.f90 files. mkmf uses only the first instance of any file name.
cd $sourcedir
find $exp_home/srcmods/ -maxdepth 1 -iname "*.f90" -o -iname "*.inc" -o -iname "*.c" -o -iname "*.h" > $workdir/tmp_pathnames
echo "Using the following sourcecode modifications:"
cat $workdir/tmp_pathnames
cat $pathnames >> $workdir/tmp_pathnames

cd $execdir
$mkmf -p fms.x -t $workdir/tmp_template -c "-Duse_libMPI -Duse_netCDF" -a $sourcedir $workdir/tmp_pathnames $sourcedir/shared/include $sourcedir/shared/memutils $sourcedir/shared/mpp/include

make -f Makefile

cd $workdir/INPUT
#--------------------------------------------------------------------------------------------------------

# set initial conditions and move to executable directory

if ( $init_cond != "" ) then
  cp $init_cond $init_cond:t
  cpio -iv  < $init_cond:t
#  rm -f $init_cond:t
endif

# name of ocean mask file, will only be used if load_mask = .true. in atmosphere_nml
set ocean_mask = ocean_mask_T42.nc

# if ocean_mask exists, move it to workdir/INPUT folder O.A. May 2014
if (-e $exp_home/input/${{ocean_mask}}) then
   cp $exp_home/input/${{ocean_mask}} ocean_mask.nc
   cd $output_dir
   cp $exp_home/input/${{ocean_mask}} ocean_mask.nc
endif

#--------------------------------------------------------------------------------------------------------

#  --- begin loop over $irun ---                                     
while ($irun <= $runs_per_script)

    cd $workdir  

    # set run length and time step, get input data and executable
    if ( $ireload == 1 && $irun == 1 ) then
      cat > input.nml <<EOF
        &main_nml
         current_time = 0,
         override = .true.,
         days   = $days,
         dt_atmos = 300 /
EOF
    else
      cat > input.nml <<EOF
        &main_nml
         days   = $days,
         dt_atmos = 300 /
EOF
    endif

    if (${{model_type}} == dry) then 
    cat >> input.nml <<EOF

      &spectral_dynamics_nml       
        damping_option          = $damping_option, 
        damping_order           = $damping_order,
        damping_coeff           = $damping_coeff,
        cutoff_wn               = 15,
        do_mass_correction      =.true.,
        do_energy_correction    =.true.,
        do_water_correction     =.false.,
        do_spec_tracer_filter   =.false.,
        use_virtual_temperature =.false.,
        vert_advect_uv          = 'second_centered',
        vert_advect_t           = 'second_centered',
        longitude_origin        = 0.,
        robert_coeff            = .04,
        raw_factor              = 0.53,
        alpha_implicit          = .5, 
        reference_sea_level_press=1.e5, 
        lon_max                 = $lon_max,
        lat_max                 = $lat_max,
        num_levels              = 30,
        num_fourier             = $num_fourier,
        num_spherical           = $num_spherical,
        fourier_inc             = 1,
        triang_trunc            =.true.,
        valid_range_t 	    = 100. 800.,
        vert_coord_option       = 'uneven_sigma',
        topography_option       = 'flat',
        surf_res                = 0.1,
        scale_heights           = 5.0,
        exponent                = 2.0, 
        omega_factor            = $omega,
        do_no_eddy_eddy         = .false. / 
      &atmosphere_nml      
        two_stream           = .false.,
        turb                 = .true.,
        ldry_convection      = .true.,
        dry_model            = .true.,
        lwet_convection      = .false.,
        mixed_layer_bc       = .false.,
        do_virtual           = .false.,
        tapio_forcing        = .false.,
        hs                   = .false.,
        bordoni_forcing      = .true.,
        atmos_water_correction = .false.,
        roughness_mom        = 0.05, 
        roughness_heat       = 0.05,
        roughness_moist      = 0.05,
        bucket               = .false./

      &vert_turb_driver_nml
        do_mellor_yamada         = .false.,
        do_shallow_conv          = .false.,
        gust_scheme              = 'constant',
        constant_gust            = 1.0,
        use_tau                  = .true.,
        do_molecular_diffusion   = $moldiff/
      
      &diffusivity_nml
        pbl_mcm                 = .true.,
        free_atm_diff           = $freediff,
        entr_ratio              = 0.0,
        mix_len	           = 30.0,
        fixed_depth             = .true.,	
        depth_0                 = 2500.0,
        frac_inner              = 0.015,
        diff_coef               = $diff_coef/

EOF
    else if (${{model_type}} == moist) then

    cat >> input.nml <<EOF    
  
      &atmosphere_nml
        two_stream           = .true.,
        turb                 = .true.,
        ldry_convection      = .false., 
        dry_model            = .false.,
        lwet_convection      = .true.,
        mixed_layer_bc       = .true.,
        do_virtual           = .true.,
        tapio_forcing        = .false., 
        hs                   = .false.,
        atmos_water_correction = .false.,
        roughness_mom        = 5e-03,
        roughness_heat       = 1e-05,
        roughness_moist      = 1e-05,
        bucket               = .false./

EOF

    else if (${{model_type}} == moist_hydro) then

    cat >> input.nml <<EOF    
  
      &atmosphere_nml
        two_stream           = .true.,
        turb                 = .true.,
        ldry_convection      = .false., 
        dry_model            = .false.,
        lwet_convection      = .true.,
        mixed_layer_bc       = .true.,
        do_virtual           = .true.,
        tapio_forcing        = .false., 
        hs                   = .false.,
        atmos_water_correction = .false.,
        roughness_mom        = 5e-03,
        roughness_heat       = 1e-05,
        roughness_moist      = 1e-05,
        bucket               = .true., 
        load_mask            = .true.,
        init_bucket_depth    = 1000., 
        init_bucket_depth_land = 1., 
        land_left            = 0.,
        land_right           = 360.,
        land_bottom          = 10.,
        land_top             = 30.,
        max_bucket_depth_land= 2., 
        robert_bucket        = 0.04,   
        raw_bucket           = 0.53,       
        damping_coeff_bucket = 200/

EOF
   endif

    cat >> input.nml <<EOF


      &grid_phys_list 
        tsfc_avg                 = $Tsfcavg, 
        delh                     = $delh,
        ka_days                  = $kadays,
        ks_days                  = $ksdays,
        Cdrag                    = $drag,
        t_strat                  = 200.0,
        sigma_b                  = $sigmab,
        sigma_lat                = $sigmalat,
        scale_height_ratio       = 3.5,
        reference_sea_level_press = 100000.,
        phi0                     = $phi0/

      &dry_convection_nml
        gamma                    = $gamma,
        tau                      = $tauc/

      &spectral_init_cond_nml
        initial_temperature  = 250.0,
        choice_of_init       = $axisymm /

      &diag_manager_nml
        mix_snapshot_average_fields = .false. /

      &radiation_nml
        albedo_value                 = 0.38,  
        lw_linear_frac               = 0.2,
        perpetual_equinox            =.true.,
        annual_mean                  =.false.,
        fixed_day                    =.false.,
        fixed_day_value              = 90.0,
        solar_constant               = 1360,
        lw_tau_exponent              = 4.0, 
        sw_tau_exponent              = 2.0,
        odp                          = 1.0,
        lw_tau0_pole                 = 1.8,
        lw_tau0_eqtr                 = 7.2,
        del_sol                      = 1.2,
        atm_abs                      = 0.22,
        days_in_year                 = 360,
        orb_long_perh                = 0,
        orb_ecc                      = 0.0,
        orb_obl                      = 23.5 /

      
      &mixed_layer_nml
        depth              = 40.0,
        qflux_amp          = 0.0,
        qflux_width        = 16.0,
        ekman_layer        = .true.,
        load_qflux         = .false.,
        evaporation        = .true.,
        depth_land         =  1.0,/


      &qe_moist_convection_nml
        tau_bm               = 7200.0,
        rhbm                 = 0.7,
        val_inc              = 0.01,
        Tmin                 = 50.,
        Tmax                 = 450. /

      &lscale_cond_nml
        do_evap              = .false./

      # requires topography_option = 'gaussian' in spectral_dynamics_nml
      &gaussian_topog_nml
        height             = 0.0,
        olon               = 90.0,
        olat               = 35.0,
        rlon               = 0.0,
        rlat               = 2.5,
        wlon               = 4.95,
        wlat               = 4.95 /

EOF
    endif

    cat $namelist >> input.nml
    cp $diagtable diag_table
    cp $fieldtable field_table
    cp $execdir/fms.x fms.x

    cp input.nml $run_dir

    
    #--------------------------------------------------------------------------------------------------------
  
    # run the model with mpirun
    set MX_RCACHE=2
    # setenv I_MPI_DEBUG 5
    # setenv OMP_NUM_THREADS 16
    # mpirun -np $NPROCS ${{workdir}}/fms.x
    # setenv SLURM_CPU_BIND cores
    # srun ${{workdir}}/fms.x

    # just before your srun
    # setenv I_MPI_DEBUG 10

    setenv I_MPI_PMI_LIBRARY "/central/slurm/install/current/lib/libpmi2.so"
    setenv I_MPI_FABRICS "shm:ofi"
    setenv I_MPI_OFI_PROVIDER "mlx"
    setenv I_MPI_DEBUG 5
    setenv I_MPI_STATS 1    

    srun -n $NPROCS ${{workdir}}/fms.x

    # launch with Slurm PMI-2
    # mpirun -np $NPROCS ${{workdir}}/fms.x
    
    #--------------------------------------------------------------------------------------------------------

    #   --- generate date for file names ---

    set date_name = `$time_stamp -eh`
    if ( $date_name == "" ) set date_name = tmp`date '+%j%H%M%S'`
    if ( -f time_stamp.out ) rm -f time_stamp.out

    #--------------------------------------------------------------------------------------------------------

    #   --- move output files to their own directories (don't combine) --- 

    if ( ! -d $output_dir/combine ) then
      mkdir -p $output_dir/combine  
    endif
    mkdir $output_dir/combine/$date_name

    foreach ncfile ( `/bin/ls *.nc *.nc.????` )
        mv $ncfile $output_dir/combine/$date_name/$date_name.$ncfile
    end

    #   --- save ascii output files to local disk ---

    foreach out (`/bin/ls *.out`)
        mv $out $output_dir/logfiles/$date_name.$out
    end

    #   --- move restart files to output directory --- 

    cd $workdir/RESTART
    set resfiles = `/bin/ls *.res*`

    if ( $#resfiles > 0 ) then
        #     --- desired filename for cpio of output restart files ---
        set restart_file = $output_dir/restart/$date_name.cpio
        if ( ! -d $restart_file:h ) mkdir -p $restart_file:h
        #     --- also save namelist and diag_table ---
        cp $workdir/{{*.nml,diag_table}} .
        set files = ( $resfiles input.nml diag_table )
        /bin/ls $files | cpio -ocv > $restart_file:t
        mv $restart_file:t $restart_file
        #     --- set up restart for next run ---
        if ( $irun < $runs_per_script ) then 
            mv -f *.res*  ../INPUT
        endif
    endif

    cd $workdir

    #--------------------------------------------------------------------------------------------------------

    #   --- write new reload information ---
    # for comparison with $start_analysis,  run_number = (ireload-1)*runs_per_script + irun
    set run_number = `expr $ireload \* $runs_per_script - $runs_per_script + $irun`
    echo Completed run $irun of $runs_per_script in srun $ireload.
    set irun_prev = $irun
    @ irun++

    # remove restart file (init_cond) that is no longer in {{reload_file}} or ${{reload_file}}_prev
    if ( -f $reload_file"_prev" ) then
       set irun_tmp = $irun
       set ireload_tmp = $ireload
       set init_cond_tmp = $init_cond
       source $reload_file"_prev"
       rm -r $init_cond
       set irun = $irun_tmp
       set ireload = $ireload_tmp
       set init_cond = $init_cond_tmp
    endif
    if ( -f $reload_file ) mv -f $reload_file $reload_file"_prev"
    
    if ( $irun <= $runs_per_script ) then
        echo "set irun         =  $irun"          >  $reload_file
    else
        @ ireload++
        echo "set irun         =  1"              >  $reload_file
    endif

    echo     "set init_cond    =  $restart_file"  >> $reload_file
    echo     "set ireload      =  $ireload"       >> $reload_file
 
    ############################# post processing ############################
    
    if (${{run_number}} < ${{start_analysis}}) then # delete data before analysis time
        rm -rf $output_dir/combine/$date_name
    endif

    # don't resubmit if model failed to build a restart file
    if ( ! -f $restart_file ) then
      echo "FATAL ERROR: model restart file not saved. Try moving ${{reload_file}}_prev to ${{reload_file}} and re-running."
      echo "ireload = $ireload, irun = $irun"
      set irun = `expr $runs_per_script + 1 `
      set ireload = `expr $num_script_runs + 1 `
    endif

end # --- loop over $irun ended ---

# rm -rf $workdir

cd $exp_home/run

if ($ireload > $num_script_runs) then
  echo "Note: not resubmitting job."
else
  echo "Submitting run $ireload."
  sbatch $run_script
endif

date

# Construct command-line arguments from defined variables
set argstr = ""

# Add arguments for each variable you want to pass (add/remove as needed)
set argstr = "$argstr --runname ${{runname}}"
set argstr = "$argstr --raw_output_dir ${{output_dir}}"
set argstr = "$argstr --days ${{days}}"
set argstr = "$argstr --runs_per_script ${{runs_per_script}}"
set argstr = "$argstr --start_analysis ${{start_analysis}}"

cd ${{analysis_dir}}

# Now call sbatch with the constructed arguments
sbatch ${{analysis_script}} $argstr

# Copy output to 
# cp -r $run_dir /resnick/groups/esm/$USER/fms_output
